# Generated by Django 4.0.5 on 2022-06-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wepapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
